version: "3.1"
name: "ssi-we-test"
services:
  api:
    image: "ssibrahimbas/ssi-we:latest"
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      MONGO_HOST: host.docker.internal
      MONGO_PORT: 27017
      MONGO_PASSWORD: ""
      MONGO_USER: ""
      MONGO_NAME: ssi-we-test
      MONGO_COLLECTION: ssi-we-test-collection
      CORS_ALLOW_ORIGINS: "*"
      CORS_ALLOW_METHODS: GET,POST,PUT,DELETE,OPTIONS
      CORS_ALLOW_HEADERS: ""
      CORS_ALLOW_CREDENTIALS: true
